export const MEALTYPES = [
  {
    id: "main_course",
    title: "Main Course",
    image: "main-course.jpg",
  },
  {
    id: "side_dish",
    title: "Side Dish",
    image: "side-dish.jpg",
  },
  {
    id: "appetizer",
    title: "Appetizer",
    image: "appetizer.jpg",
  },
  {
    id: "salad",
    title: "Salad",
    image: "salad.jpg",
  },
  {
    id: "soup",
    title: "Soup",
    image: "soup.jpg",
  },
  {
    id: "snack",
    title: "Snack",
    image: "snack.jpg",
  },
  {
    id: "dessert",
    title: "Dessert",
    image: "dessert.jpg",
  },
  {
    id: "breakfast",
    title: "Breakfast",
    image: "breakfast.jpg",
  },
  {
    id: "sauce",
    title: "Sauce",
    image: "sauce.jpg",
  },
  {
    id: "drink",
    title: "Drink",
    image: "drink.jpg",
  },
];

export const CUISINES = [
  "African",
  "American",
  "British",
  "Cajun",
  "Caribbean",
  "Chinese",
  "Eastern European",
  "European",
  "French",
  "German",
  "Greek",
  "Indian",
  "Irish",
  "Italian",
  "Japanese",
  "Jewish",
  "Korean",
  "Latin American",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Nordic",
  "Southern",
  "Spanish",
  "Thai",
  "Vietnamese",
];

export const DIET = [
  "Gluten Free",
  "Ketogenic",
  "Vegetarian",
  "Lacto-Vegetarian",
  "Ovo-Vegetarian",
  "Vegan",
  "Pescetarian",
  "Paleo",
  "Primal",
  "Low FODMAP",
  "Whole30",
];

export const INCLUDE_INGREDIENTS = [
  "AddBean",
  "Beef",
  "Cheese",
  "Chicken",
  "Chicken Breast",
  "Chicken Thigh",
  "Chocolate",
  "Egg",
  "Fruit",
  "Game",
  "Grains",
  "Ground Beef",
  "Lamb",
  "Pickle",
  "Pork",
  "Potato",
  "Seafood",
  "Summer Squash",
  "Swiss Chard",
  "Vegetable",
];
